site_name: "PowerShell 中文文档"
site_description: "Have a smack at translating PowerShell documentations to Chinese, help learning and understanding"
site_author: jx.zeng
site_url: "https://bash.myportable.fun"
repo_url: "https://github.com/nophDog/powershell-ch"
copyright: "CH-PowerShell is released under <a href='https://github.com/nophDog/bash-ch/blob/master/README.md'>GPL-v3 license</a>"

theme: material

nav:
  - Home: index.md
  - PowerShell About_:
      - Alias_Provider: about/about_Alias_Provider.md
      - Aliases: about/about_Aliases.md
      - Arithmetic_Operators: about/about_Arithmetic_Operators.md
      - Arrays: about/about_Arrays.md
      - Assignment_Operators: about/about_Assignment_Operators.md
  - About: about.md
